export const imagePaths = {
  professional: {
    candidate: '/images/professional/candidate.jpg',
    aboutProfile: '/images/professional/about-profile.jpg',
    gtmokhadr: '/images/professional/gtmokhadr.jpg',
    techEndorsement: '/images/professional/tech-endorsement.jpg',
    techAdvisory: '/images/professional/tech-advisory.jpg',
    veteranLeadership: '/images/professional/veteran-leadership.jpg',
    publicSpeakingWalmart: '/images/professional/publicspeakingwalmart.jpg',
    storeManager: '/images/professional/store manager.jpg',
    warehouseHourlyStaff: '/images/professional/warehousehourlystaff.jpg',
    warehouseLeadership: '/images/professional/warehouse leadershippic.jpg',
    leadershipTeam: '/images/professional/ledaershipteam.jpg',
    walmartPic: '/images/professional/walmartpic.jpg',
    walmartCheck: '/images/professional/Walmartcheck.JPG',
    amazonFlow: '/images/professional/amazonflow.jpg',
    amazonCrew: '/images/professional/amazoncrew.jpg',
  },
  personal: {
    family: '/images/personal/family.jpg',
    withDaughters: '/images/personal/withdaughters.jpg',
    worldSeries: '/images/personal/world series.jpg',
    iraq: '/images/personal/iraq.jpg',
    iraq1: '/images/personal/iraq1.jpg',
    navy: '/images/personal/navy.jpg',
    youngFamily: '/images/personal/youngerfamilyphoto.jpg',
    houstonZoo: '/images/personal/houstonzoo.jpg',
    cowboyHat: '/images/personal/cowboyhatwithashley.jpg',
    parade: '/images/personal/parade.jpg',
    merica: '/images/personal/merica.jpg',
    volunteering: '/images/personal/volunteering.jpg',
    coolCouple: '/images/personal/cool couple.jpg',
    nickAndAshley: '/images/personal/nick and ashley.jpg',
    daughterChamps: '/images/personal/daughter state knowledge bowl champs.jpg',
    kidkff: '/images/personal/kidkff.jpg',
    thinkerHeadshot: '/images/personal/thinkerheadshot.jpg',
  },
  platform: {
    hero: '/images/platform-hero.jpg',
    economy: '/images/economy.jpg',
    education: '/images/education.jpg',
    healthcare: '/images/healthcare.jpg',
    infrastructure: '/images/infrastructure.jpg',
    safety: '/images/safety.jpg',
    fiscal: '/images/fiscal.jpg',
    cybersecurity: '/images/cybersecurity.jpg',
  },
  contact: {
    hero: '/images/contact-hero.jpg',
    email: '/images/contact-email.jpg',
    phone: '/images/contact-phone.jpg',
    office: '/images/contact-office.jpg',
  },
  volunteer: {
    hero: '/images/volunteer-hero.jpg',
    impact: '/images/volunteer-impact.jpg',
    digital: '/images/digital-volunteer.jpg',
    eventPlanning: '/images/event-planning.jpg',
    phoneBanking: '/images/phone-banking.jpg',
    veteranOutreach: '/images/veteran-outreach.jpg',
    townHall: '/images/town-hall.jpg',
  },
  news: {
    hero: '/images/news-hero.jpg',
  },
  general: {
    platformCta: '/images/platform-cta.jpg',
    communityTech: '/images/community-tech.jpg',
    digitalPlatform: '/images/digital-platform.jpg',
  }
}; 