version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: campaign_db
    environment:
      POSTGRES_USER: campaign_user
      POSTGRES_PASSWORD: campaign_password
      POSTGRES_DB: campaign_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 